# Generated by Django 4.1.2 on 2022-11-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='userid',
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
