# Generated by Django 4.1.2 on 2022-11-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_login_userid_alter_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='passwd',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='login',
            name='uname',
            field=models.CharField(max_length=50),
        ),
    ]
