# Generated by Django 4.1.2 on 2022-12-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_product_add_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add',
            name='image',
            field=models.ImageField(default='a', upload_to='image/', verbose_name='image'),
        ),
    ]
