# Generated by Django 4.1.2 on 2022-12-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_product_add_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category_add',
        ),
    ]
